// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class TodoDetailNative {
  TodoDetailNative({
    required this.id,
    this.description,
    this.category,
    this.priority,
    this.dueDate,
    this.imageUrl,
  });

  int id;

  String? description;

  String? category;

  int? priority;

  int? dueDate;

  String? imageUrl;

  Object encode() {
    return <Object?>[
      id,
      description,
      category,
      priority,
      dueDate,
      imageUrl,
    ];
  }

  static TodoDetailNative decode(Object result) {
    result as List<Object?>;
    return TodoDetailNative(
      id: result[0]! as int,
      description: result[1] as String?,
      category: result[2] as String?,
      priority: result[3] as int?,
      dueDate: result[4] as int?,
      imageUrl: result[5] as String?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TodoDetailNative) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return TodoDetailNative.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class TodoNativeApi {
  /// Constructor for [TodoNativeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TodoNativeApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<TodoDetailNative> fetchTodoDetail(int id) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ultra_mobile.TodoNativeApi.fetchTodoDetail$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[id]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as TodoDetailNative?)!;
    }
  }
}

abstract class NotificationActionApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onNotificationAction(int todoId, String action);

  static void setUp(NotificationActionApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ultra_mobile.NotificationActionApi.onNotificationAction$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ultra_mobile.NotificationActionApi.onNotificationAction was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_todoId = (args[0] as int?);
          assert(arg_todoId != null,
              'Argument for dev.flutter.pigeon.ultra_mobile.NotificationActionApi.onNotificationAction was null, expected non-null int.');
          final String? arg_action = (args[1] as String?);
          assert(arg_action != null,
              'Argument for dev.flutter.pigeon.ultra_mobile.NotificationActionApi.onNotificationAction was null, expected non-null String.');
          try {
            api.onNotificationAction(arg_todoId!, arg_action!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
