// DANGER: This file should be GENERATED by build_runner.
// Do not write this by hand. Use it as a reference for debugging.

import 'package:hive/hive.dart';
import 'todo.dart';

class TodoAdapter extends TypeAdapter<Todo> {
  @override
  final int typeId = 0;

  @override
  Todo read(BinaryReader reader) {
    // This reads the fields in the exact order they were written.
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };

    return Todo(
      id: fields[0] as int,
      todo: fields[1] as String,
      completed: fields[2] as bool,
      userId: fields[3] as int,
      description: fields[4] as String?,
      dueDate: fields[5] as DateTime?,
      priority: fields[6] as int?,
      category: fields[7] as String?,
      imagePath: fields[8] as String?,
      reminderTime: fields[9] as DateTime?,
      isFavorite: fields[10] as bool?,
      createdAt: fields[11] as String?,
      updatedAt: fields[12] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, Todo obj) {
    // This writes all 13 fields (0 to 12)
    writer
      ..writeByte(13)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.todo)
      ..writeByte(2)
      ..write(obj.completed)
      ..writeByte(3)
      ..write(obj.userId)
      ..writeByte(4)
      ..write(obj.description)
      ..writeByte(5)
      ..write(obj.dueDate)
      ..writeByte(6)
      ..write(obj.priority)
      ..writeByte(7)
      ..write(obj.category)
      ..writeByte(8)
      ..write(obj.imagePath)
      ..writeByte(9)
      ..write(obj.reminderTime)
      ..writeByte(10)
      ..write(obj.isFavorite)
      ..writeByte(11)
      ..write(obj.createdAt)
      ..writeByte(12)
      ..write(obj.updatedAt);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
